export interface SeedSpecies {
  slug: string;
  nameTh: string;
  nameEn: string;
  nameSci: string;
  aliases: string[];
  family: string;
  summary: string;
  light: "full_sun" | "partial" | "shade" | "indoor_bright" | "low_light";
  waterNeed: "low" | "medium" | "high";
  placement: ("indoor" | "outdoor" | "balcony" | "bathroom")[];
  difficulty: number;
  petSafe: "safe" | "toxic" | "unknown";
  matureSize: "xs" | "sm" | "md" | "lg" | "xl";
  matureHeightCm: number;
  growthRate: "slow" | "medium" | "fast";
  soilMix: string;
  fertilizerNote: string;
  propagation: string;
  shopNote: string;
  stockStatus: "in_stock" | "made_to_order" | "seasonal";
  images: {
    url: string;
    altTh: string;
    isPrimary: boolean;
  }[];
  careTemplate: {
    waterDaysHot: number;
    waterDaysRainy: number;
    waterDaysCool: number;
    fertilizeDays: number;
    fertilizePauseMonths: number[];
    repotMonths: number;
    pruneDays?: number;
    pestCheckDays: number;
    notesTh: string;
  };
  problems: {
    symptomTh: string;
    causeTh: string;
    fixTh: string;
    severity: "low" | "medium" | "high";
  }[];
}

export const SEED_SPECIES: SeedSpecies[] = [
  {
    slug: "monstera-albo-variegata",
    nameTh: "มอนสเตอร่าด่าง อัลโบ",
    nameEn: "Variegated Monstera Albo",
    nameSci: "Monstera deliciosa 'Albo Variegata'",
    aliases: ["มอนด่าง", "อัลโบ", "มอนสเตอร่าอัลโบ", "Albo"],
    family: "Araceae (วงศ์บอน)",
    summary: "ราชินีไม้ใบยอดนิยม ลวดลายด่างขาวหิมะตัดกับสีเขียวเข้ม เพิ่มความหรูหราให้ทุกมุมบ้าน",
    light: "indoor_bright",
    waterNeed: "medium",
    placement: ["indoor", "balcony"],
    difficulty: 3,
    petSafe: "toxic",
    matureSize: "lg",
    matureHeightCm: 180,
    growthRate: "medium",
    soilMix: "กาบมะพร้าวสับ 40% + เพอร์ไลท์ 25% + หินภูเขาไฟ 20% + มูลไส้เดือน 15% (ระบายน้ำดีพิเศษ ห้ามดินแน่น)",
    fertilizerNote: "ออสโมโค้ทสูตรละลายช้า 13-13-13 ทุก 3 เดือน เสริมฮิวมิคแอซิดบำรุงรากเดือนละครั้ง",
    propagation: "ตัดชำข้อที่มีรากอากาศ แช่น้ำหรืออบในสแฟกนัมมอส",
    shopNote: "ข้อควรระวังสำคัญของอัลโบคือส่วนด่างขาวจะไหม้ง่ายมากถ้าโดนแดดตรงๆ ให้วางห่างหน้าต่าง 1-2 เมตร และอย่ารดน้ำโดนใบขาวช่วงบ่าย",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=1200&q=80",
        altTh: "มอนสเตอร่าด่าง อัลโบ ถ่ายที่เรือนเพาะชำของร้าน",
        isPrimary: true,
      },
      {
        url: "https://images.unsplash.com/photo-1617173944883-6ffbd35d584d?auto=format&fit=crop&w=1200&q=80",
        altTh: "ลักษณะรอยด่างขาวคมชัดบนใบมอนสเตอร่า",
        isPrimary: false,
      }
    ],
    careTemplate: {
      waterDaysHot: 3,
      waterDaysRainy: 6,
      waterDaysCool: 5,
      fertilizeDays: 45,
      fertilizePauseMonths: [12, 1],
      repotMonths: 12,
      pruneDays: 90,
      pestCheckDays: 14,
      notesTh: "เช็คโคนต้นและใช้นิ้วจิ้มดินลึก 2 นิ้ว หากแห้งสนิทค่อยรดน้ำ รดจนไหลออกก้นกระถาง",
    },
    problems: [
      {
        symptomTh: "ขอบใบด่างขาวเปลี่ยนเป็นสีน้ำตาลแห้งกรอบ",
        causeTh: "ความชื้นในอากาศต่ำเกินไป หรือโดนแสงแดดบ่ายกระทบตรงๆ",
        fixTh: "ขยับหลบแดดส่องตรง ฉีดสเปรย์ละอองน้ำรอบๆ ต้น (อย่าพ่นเปียกโชกบนใบขาว)",
        severity: "medium",
      },
      {
        symptomTh: "ใบเหลืองนิ่มจากใบล่างและก้านเริ่มอ่อน",
        causeTh: "ดินชื้นสะสมเกินไป รากเริ่มขาดออกซิเจนหรือเน่า",
        fixTh: "หยุดรดน้ำทันที ควักดูราก ตัดรากที่เน่าทิ้ง แช่ยากันรา และเปลี่ยนวัสดุปลูกโปร่ง",
        severity: "high",
      }
    ],
  },
  {
    slug: "ficus-lyrata",
    nameTh: "ไทรใบสัก",
    nameEn: "Fiddle Leaf Fig",
    nameSci: "Ficus lyrata",
    aliases: ["ไทรใบสักฟอร์มต้น", "Fiddle Leaf"],
    family: "Moraceae",
    summary: "ไม้กระถางทรงประติมากรรม ฟอร์มสง่างาม ใบใหญ่หนาสีเขียวเข้ม ชูความมินิมอลและลักชัวรี่",
    light: "indoor_bright",
    waterNeed: "low",
    placement: ["indoor", "balcony"],
    difficulty: 3,
    petSafe: "toxic",
    matureSize: "xl",
    matureHeightCm: 250,
    growthRate: "slow",
    soilMix: "ดินก้ามปูหมัก 40% + กาบมะพร้าวสับ 30% + เพอร์ไลท์ 20% + ปุ๋ยคอกเก่า 10%",
    fertilizerNote: "ปุ๋ยเม็ดละลายช้าทุก 2-3 เดือน เช็ดใบด้วยน้ำผสมน้ำมันสะเดาเบาๆ ให้ใบเงา",
    propagation: "ปักชำกิ่งยอด หรือตอนกิ่ง",
    shopNote: "ไทรใบสักไม่ชอบให้ย้ายที่บ่อย เมื่อหามุมที่แสงถึงและน้องแตกใบใหม่แล้ว ให้อยู่มุมเดิม เช็ดฝุ่นออกจากใบเดือนละ 2 ครั้งเพื่อช่วยการสังเคราะห์แสง",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1545241047-6083a3684587?auto=format&fit=crop&w=1200&q=80",
        altTh: "ไทรใบสักในกระถางเซรามิก ถ่ายที่โชว์รูมร้าน",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 4,
      waterDaysRainy: 7,
      waterDaysCool: 6,
      fertilizeDays: 60,
      fertilizePauseMonths: [12],
      repotMonths: 18,
      pestCheckDays: 14,
      notesTh: "ชอบดินแห้งสลับเปียก ห้ามมีน้ำขังในจานรอง รดน้ำจนชุ่มแล้วเทน้ำขังทิ้ง",
    },
    problems: [
      {
        symptomTh: "ใบมีจุดสีน้ำตาลแดงกระจายบนใบอ่อน (Edema)",
        causeTh: "การดูดน้ำไม่สม่ำเสมอ เซลล์ใบแตกจากแรงดันน้ำ",
        fixTh: "ปรับรอบการรดน้ำให้สม่ำเสมอ อย่าปล่อยให้ดินแห้งผากแล้วรดน้ำโชกเกินไป",
        severity: "low",
      },
      {
        symptomTh: "ใบร่วงจำนวนมากจากโคนต้น",
        causeTh: "แสงสว่างไม่เพียงพอ หรือเพิ่งเปลี่ยนตำแหน่งวางใหม่",
        fixTh: "วางในจุดที่รับแสงหน้าต่างสว่างอย่างน้อย 5-6 ชม. ต่อวัน",
        severity: "medium",
      }
    ],
  },
  {
    slug: "ficus-elastica-burgundy",
    nameTh: "ยางอินเดียดำ เบอร์กันดี",
    nameEn: "Burgundy Rubber Tree",
    nameSci: "Ficus elastica 'Burgundy'",
    aliases: ["ยางอินเดีย", "ยางดำ", "Rubber Tree"],
    family: "Moraceae",
    summary: "ใบหนาสีเขียวเข้มเกือบดำ ยอดแดงเลือดนก เลี้ยงง่าย ทรงพลัง ฟอกอากาศดีเยี่ยม",
    light: "indoor_bright",
    waterNeed: "low",
    placement: ["indoor", "balcony", "outdoor"],
    difficulty: 1,
    petSafe: "toxic",
    matureSize: "lg",
    matureHeightCm: 200,
    growthRate: "medium",
    soilMix: "ดินใบก้ามปูร่วนซุย ผสมกาบมะพร้าวสับและทรายหยาบ ระบายน้ำคล่อง",
    fertilizerNote: "ปุ๋ยบำรุงใบ 16-16-16 หรือปุ๋ยคอกหมัก ทุก 2 เดือน",
    propagation: "ปักชำกิ่งในน้ำ หรือตอนกิ่ง",
    shopNote: "พันธุ์นี้ทนมากที่สุดในตระกูลยางอินเดีย เลี้ยงในห้องแอร์ได้สบาย แค่ตั้งใกล้กระจก รดน้ำสัปดาห์ละครั้งก็รอดสบาย",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1596724803362-e6113b2e75dc?auto=format&fit=crop&w=1200&q=80",
        altTh: "ยางอินเดียดำฟอร์มพุ่มแน่น ถ่ายที่ร้าน",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 4,
      waterDaysRainy: 7,
      waterDaysCool: 6,
      fertilizeDays: 45,
      fertilizePauseMonths: [],
      repotMonths: 18,
      pestCheckDays: 20,
      notesTh: "ทนแล้งได้ดี รอนิ้วจิ้มดินแห้งสนิทค่อยรดน้ำ",
    },
    problems: [
      {
        symptomTh: "ใบซีด ไม่เงางาม สีเขียวอ่อนลง",
        causeTh: "แสงน้อยเกินไป หรือมีคราบฝุ่นเกาะบนผิวใบหนา",
        fixTh: "ย้ายเข้าใกล้แสงแดดรำไร และใช้ผ้าชุบน้ำเช็ดใบเบาๆ",
        severity: "low",
      }
    ],
  },
  {
    slug: "zamioculcas-zamiifolia-raven",
    nameTh: "กวักมรกตดำ ราเวน",
    nameEn: "Black Raven ZZ Plant",
    nameSci: "Zamioculcas zamiifolia 'Raven'",
    aliases: ["กวักดำ", "กวักมรกตใบดำ", "Raven ZZ"],
    family: "Araceae",
    summary: "ต้นไม้มงคลเรียกทรัพย์ ใบยอดอ่อนสีเขียวมะนาวก่อนเปลี่ยนเป็นสีดำขลับมันวาว เลี้ยงง่ายที่สุดในโลก",
    light: "low_light",
    waterNeed: "low",
    placement: ["indoor", "bathroom", "balcony"],
    difficulty: 1,
    petSafe: "toxic",
    matureSize: "md",
    matureHeightCm: 80,
    growthRate: "slow",
    soilMix: "ดินปลูกผสมหินภูเขาไฟและเพอร์ไลท์ 40% เน้นระบายน้ำรวดเร็ว หัวใต้ดินไม่ชอบแฉะ",
    fertilizerNote: "ปุ๋ยละลายช้าเม็ดเล็กทุก 3 เดือน ไม่ต้องการปุ๋ยบ่อย",
    propagation: "แยกหน่อ หรือปักชำก้านใบเดี่ยว",
    shopNote: "ร้านเราทดสอบแล้ว กวักดำอยู่รอดได้แม้ลืมรดน้ำนาน 3 สัปดาห์ สิ่งเดียวที่ฆ่ามันได้คือน้ำขังจนหัวเน่า",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1632207691143-643e2a9a9361?auto=format&fit=crop&w=1200&q=80",
        altTh: "กวักมรกตดำในกระถางดินเผามินิมอล",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 7,
      waterDaysRainy: 12,
      waterDaysCool: 10,
      fertilizeDays: 90,
      fertilizePauseMonths: [11, 12, 1],
      repotMonths: 24,
      pestCheckDays: 30,
      notesTh: "รดน้ำเมื่อดินแห้งสนิททั้งกระถางเท่านั้น หัวใต้ดินสะสมน้ำได้ดีมาก",
    },
    problems: [
      {
        symptomTh: "ก้านใบล่างเหลืองนิ่ม หลุดง่ายจากโคน",
        causeTh: "รดน้ำถี่เกินไป ดินระบายน้ำไม่ทัน หัวใต้ดินเริ่มเน่า",
        fixTh: "งดน้ำทันที ถอดกระถางผึ่งลม ตัดหัวที่เน่าทิ้ง",
        severity: "high",
      }
    ],
  },
  {
    slug: "sansevieria-trifasciata",
    nameTh: "ลิ้นมังกรดาบเงิน ซิลเวอร์ควีน",
    nameEn: "Silver Queen Snake Plant",
    nameSci: "Sansevieria trifasciata 'Silver Queen'",
    aliases: ["ลิ้นมังกร", "ดาบเงิน", "Snake Plant"],
    family: "Asparagaceae",
    summary: "สุดยอดไม้ฟอกอากาศ คายออกซิเจนตอนกลางคืน สีเทาเงินสว่าง ทนทานทุกสภาพแสง",
    light: "low_light",
    waterNeed: "low",
    placement: ["indoor", "balcony", "outdoor", "bathroom"],
    difficulty: 1,
    petSafe: "toxic",
    matureSize: "md",
    matureHeightCm: 90,
    growthRate: "slow",
    soilMix: "ดินแคคตัส หรือดินร่วนผสมทรายหยาบและหินภูเขาไฟ ระบายน้ำแห้งไว",
    fertilizerNote: "ปุ๋ยคอกเก่าหรือปุ๋ยละลายช้า ปีละ 2 ครั้ง",
    propagation: "ตัดใบปักชำ หรือแยกหน่อ",
    shopNote: "เหมาะที่สุดกับการวางในห้องนอนเพราะปล่อยออกซิเจนยามค่ำคืน ทนแล้งมาก รดน้ำเดือนละ 2-3 ครั้งพอ",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1593482892290-f54927ae1bf6?auto=format&fit=crop&w=1200&q=80",
        altTh: "ลิ้นมังกรดาบเงินฟอร์มสวย",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 7,
      waterDaysRainy: 14,
      waterDaysCool: 10,
      fertilizeDays: 90,
      fertilizePauseMonths: [],
      repotMonths: 24,
      pestCheckDays: 30,
      notesTh: "รดน้ำรอบขอบกระถาง อย่าเทน้ำขังในใจกลางยอดใบ",
    },
    problems: [
      {
        symptomTh: "โคนใบนิ่มยุบและเปลี่ยนเป็นสีน้ำตาลใส",
        causeTh: "น้ำขังตรงโคนต้น ดินแฉะสะสม",
        fixTh: "งดน้ำ ผึ่งแดดอ่อน ตัดส่วนที่เน่าทิ้ง",
        severity: "high",
      }
    ],
  },
  {
    slug: "philodendron-pink-princess",
    nameTh: "ฟิโลเดนดรอน พิ้งค์ปริ๊นเซส",
    nameEn: "Philodendron Pink Princess",
    nameSci: "Philodendron erubescens 'Pink Princess'",
    aliases: ["พิ้งค์ปริ๊นเซส", "ฟิโลชมพู", "PPP"],
    family: "Araceae",
    summary: "เจ้าหญิงแห่งไม้ใบ ด่างชมพูหวานสดใสตัดกับใบสีเขียวมะกอกเข้ม ทรงคุณค่าน่าสะสม",
    light: "indoor_bright",
    waterNeed: "medium",
    placement: ["indoor", "balcony"],
    difficulty: 2,
    petSafe: "toxic",
    matureSize: "md",
    matureHeightCm: 100,
    growthRate: "medium",
    soilMix: "สแฟกนัมมอส + กาบมะพร้าวสับ + เพอร์ไลท์ + เปลือกสน ความโปร่ง 70%",
    fertilizerNote: "ปุ๋ยเกล็ดสูตรเสมอเจือจางพ่นทางใบทุก 2 สัปดาห์",
    propagation: "ตัดข้อปักชำ เลี้ยงรากในน้ำ",
    shopNote: "อยากให้ชมพูออกเยอะ ต้องให้แสงสว่างทางอ้อมที่เข้มพอ หากวางในที่มืดใบจะกลับมาเขียวล้วน",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1620127814146-d1a5be298980?auto=format&fit=crop&w=1200&q=80",
        altTh: "ฟิโลเดนดรอน พิ้งค์ปริ๊นเซส ด่างชมพูสวย",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 3,
      waterDaysRainy: 6,
      waterDaysCool: 5,
      fertilizeDays: 30,
      fertilizePauseMonths: [12],
      repotMonths: 12,
      pestCheckDays: 14,
      notesTh: "ชอบความชื้นในอากาศสูง แต่ดินต้องไม่แฉะแช่น้ำ",
    },
    problems: [
      {
        symptomTh: "ใบใหม่ออกมาสีเขียวล้วน ไม่มีด่างชมพู",
        causeTh: "แสงสว่างไม่เพียงพอ พืชปรับตัวสร้างคลอโรฟิลล์เพิ่ม",
        fixTh: "ขยับเข้าใกล้หน้าต่าง หรือเสริมไฟปลูกต้นไม้ (Grow light)",
        severity: "low",
      }
    ],
  },
  {
    slug: "homalomena-rubescens-variegata",
    nameTh: "เสน่ห์จันทน์ประกายดาว",
    nameEn: "Homalomena 'Sparkling Star'",
    nameSci: "Homalomena rubescens 'Variegata'",
    aliases: ["ประกายดาว", "จันทน์ประกายดาว", "เสน่ห์จันทน์ด่าง"],
    family: "Araceae",
    summary: "ไม้มงคลโบราณเสริมเสน่ห์เมตตา ลายด่างชมพูและขาวกระจายทั่วใบเหมือนดวงดาวบนท้องฟ้า",
    light: "indoor_bright",
    waterNeed: "medium",
    placement: ["indoor", "balcony"],
    difficulty: 3,
    petSafe: "toxic",
    matureSize: "md",
    matureHeightCm: 70,
    growthRate: "slow",
    soilMix: "พีทมอส 30% + กาบมะพร้าวสับเล็ก 40% + เพอร์ไลท์ 20% + หินภูเขาไฟ 10%",
    fertilizerNote: "ปุ๋ยอินทรีย์เม็ดหรือมูลไส้เดือน 1 ช้อนโต๊ะทุกเดือน",
    propagation: "แยกหน่อชิดโคนต้น",
    shopNote: "อย่าให้ลมแอร์เป่าโดนใบโดยตรง ก้านจะตกและใบเหี่ยวเร็ว เสน่ห์จันทน์ชอบความชื้นนิ่งๆ แดดรำไร",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1200&q=80",
        altTh: "เสน่ห์จันทน์ประกายดาว ลายด่างพราว",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 3,
      waterDaysRainy: 5,
      waterDaysCool: 4,
      fertilizeDays: 30,
      fertilizePauseMonths: [],
      repotMonths: 12,
      pestCheckDays: 14,
      notesTh: "รักษาความชื้นสม่ำเสมอ รดน้ำเมื่อผิวดินเริ่มแห้ง",
    },
    problems: [
      {
        symptomTh: "ใบเหลืองเฉา ก้านทอดนอนลงกับขอบกระถาง",
        causeTh: "ขาดน้ำ หรือโดนลมร้อน/ลมแอร์เป่ากระทบแรง",
        fixTh: "รดน้ำให้ชุ่ม ย้ายหลบลมเป่า ก้านจะฟื้นตัวตั้งตรงใน 2-3 ชม.",
        severity: "medium",
      }
    ],
  },
  {
    slug: "alocasia-black-velvet",
    nameTh: "อโลคาเซีย แบล็คเวลเวท",
    nameEn: "Alocasia Black Velvet",
    nameSci: "Alocasia reginula 'Black Velvet'",
    aliases: ["แบล็คเวลเวท", "แก้วสารพัดนึกดำ"],
    family: "Araceae",
    summary: "ใบกำมะหยี่สีดำเข้มตัดกับเส้นใบสีเงินสะท้อนแสง ทรงพุ่มกะทัดรัด หรูหราเหนือกาลเวลา",
    light: "indoor_bright",
    waterNeed: "low",
    placement: ["indoor", "balcony"],
    difficulty: 3,
    petSafe: "toxic",
    matureSize: "sm",
    matureHeightCm: 40,
    growthRate: "slow",
    soilMix: "วัสดุปลูกโปร่งพิเศษ เปลือกสนไซส์เล็ก + เพอร์ไลท์ + ดินพีทมอสเล็กน้อย",
    fertilizerNote: "ปุ๋ยเกล็ดสูตร 20-20-20 เจือจาง 1/4 ของฉลาก เดือนละ 1 ครั้ง",
    propagation: "แยกไข่ (Corms) ที่ฝังในดินไปเพาะชำ",
    shopNote: "ตระกูลอโลคาเซียไวต่อน้ำขังมาก ถ้ารดน้ำเยอะเกินไป ใบจะสลัดทิ้งเหลืองทีละใบ ให้รอจนดินแห้งเกือบหมดกระถางค่อยรด",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1600411833196-7c1f6b1a8b90?auto=format&fit=crop&w=1200&q=80",
        altTh: "อโลคาเซีย แบล็คเวลเวท ใบกำมะหยี่สีดำขรึม",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 4,
      waterDaysRainy: 7,
      waterDaysCool: 6,
      fertilizeDays: 45,
      fertilizePauseMonths: [12, 1],
      repotMonths: 12,
      pestCheckDays: 10,
      notesTh: "ระวังไรแดงใต้ใบ หมั่นฉีดพ่นละอองน้ำล้างใต้ใบเป็นประจำ",
    },
    problems: [
      {
        symptomTh: "ใบเก่าล่างสุดเหลืองแล้วแห้งเหี่ยวลง",
        causeTh: "กำลังผลัดใบเพื่อสร้างใบใหม่ หรือดินแฉะเกินไป",
        fixTh: "ถ้ามียอดใหม่แทงขึ้นมาถือว่าปกติ แต่ถ้าไม่มี ให้ลดปริมาณการรดน้ำลง",
        severity: "low",
      }
    ],
  },
  {
    slug: "spathiphyllum-sensation",
    nameTh: "เดหลีจักรพรรดิ์ เซนเซชั่น",
    nameEn: "Peace Lily Sensation",
    nameSci: "Spathiphyllum 'Sensation'",
    aliases: ["เดหลีใบใหญ่", "เดหลีจักรพรรดิ์", "Peace Lily"],
    family: "Araceae",
    summary: "ต้นไม้ที่บอกเวลาหิวน้ำได้เอง ใบเขียวเข้มเป็นลอนคลื่น ดอกสีขาวบริสุทธิ์ ปลอดภัยและฟอกสารพิษ",
    light: "shade",
    waterNeed: "high",
    placement: ["indoor", "bathroom", "balcony"],
    difficulty: 1,
    petSafe: "toxic",
    matureSize: "lg",
    matureHeightCm: 150,
    growthRate: "medium",
    soilMix: "ดินร่วนผสมกาบมะพร้าวสับและพีทมอส อุ้มความชื้นได้ดีแต่ไม่ขังแฉะ",
    fertilizerNote: "ปุ๋ยบำรุงดอกและใบสูตรเสมอ ทุกเดือน",
    propagation: "แยกกอต้นลูก",
    shopNote: "ถ้าเห็นใบเริ่มตกห้อย แปลว่าน้องกระหายน้ำมาก ให้รดน้ำชุ่มๆ ทันที จะกลับมาเต่งตึงชูช่อเหมือนเดิมในไม่กี่ชั่วโมง",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1593691509543-c55fb32e7355?auto=format&fit=crop&w=1200&q=80",
        altTh: "เดหลีใบใหญ่ ดอกขาวสง่า",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 2,
      waterDaysRainy: 4,
      waterDaysCool: 3,
      fertilizeDays: 30,
      fertilizePauseMonths: [],
      repotMonths: 12,
      pestCheckDays: 20,
      notesTh: "ชอบดินชื้นปานกลาง อย่าปล่อยให้ดินแห้งสนิทจนใบเหี่ยวบ่อยๆ",
    },
    problems: [
      {
        symptomTh: "ปลายใบแห้งเป็นสีน้ำตาลเข้ม",
        causeTh: "คลอรีนในน้ำประปา หรือความชื้นสัมพัทธ์ในอากาศต่ำ",
        fixTh: "พักน้ำประปาทิ้งไว้ 1 คืนก่อนรด หรือใช้น้ำกรอง",
        severity: "low",
      }
    ],
  },
  {
    slug: "epipremnum-aureum",
    nameTh: "พลูด่าง ราชินีหินอ่อน",
    nameEn: "Marble Queen Pothos",
    nameSci: "Epipremnum aureum 'Marble Queen'",
    aliases: ["พลูด่าง", "พลูงาช้าง", "ราชินีหินอ่อน", "Pothos"],
    family: "Araceae",
    summary: "ไม้เลื้อยยอดนิยม เลี้ยงง่ายโตไว ลายหินอ่อนขาวแซมเขียว ปลูกลงดินหรือแช่น้ำแจกันแก้วก็สวย",
    light: "low_light",
    waterNeed: "medium",
    placement: ["indoor", "balcony", "bathroom"],
    difficulty: 1,
    petSafe: "toxic",
    matureSize: "md",
    matureHeightCm: 60,
    growthRate: "fast",
    soilMix: "ดินผสมกาบมะพร้าวสับทั่วไป ปลูกง่ายปรับตัวได้ทุกสภาพ",
    fertilizerNote: "ปุ๋ยน้ำบำรุงใบเจือจางเดือนละครั้ง",
    propagation: "ตัดข้อกิ่งแช่น้ำ รากงอกภายใน 7-10 วัน",
    shopNote: "วางบนชั้นหนังสือ ปล่อยให้กิ่งเลื้อยห้อยลงมา สร้างบรรยากาศผ่อนคลายในห้องทำงานได้อย่างดีเยี่ยม",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1597055181300-e3633a917c9c?auto=format&fit=crop&w=1200&q=80",
        altTh: "พลูด่างราชินีหินอ่อน เลื้อยสวยในกระถางแขวน",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 3,
      waterDaysRainy: 5,
      waterDaysCool: 4,
      fertilizeDays: 45,
      fertilizePauseMonths: [],
      repotMonths: 18,
      pestCheckDays: 20,
      notesTh: "รดน้ำเมื่อสัมผัสผิวดินแล้วรู้สึกแห้ง",
    },
    problems: [
      {
        symptomTh: "เถายาวเก้งก้าง ใบห่างกัน",
        causeTh: "แสงน้อยเกินไป ต้นพยายามยืดหาแสง",
        fixTh: "ตัดเล็มยอดให้แตกพุ่มแน่นขึ้น และขยับเข้าใกล้แสงรำไร",
        severity: "low",
      }
    ],
  },
  {
    slug: "peperomia-prostrata",
    nameTh: "เปปเปอร์โรเมีย แตงโม",
    nameEn: "Watermelon Peperomia",
    nameSci: "Peperomia argyreia",
    aliases: ["เปปเปอร์แตงโม", "แตงโม"],
    family: "Piperaceae",
    summary: "ใบกลมน่ารัก ลายทางสีเงินพาดผ่านเหมือนผลแตงโม ปลอดภัยกับน้องหมาน้องแมว 100%",
    light: "indoor_bright",
    waterNeed: "low",
    placement: ["indoor", "balcony"],
    difficulty: 2,
    petSafe: "safe",
    matureSize: "xs",
    matureHeightCm: 25,
    growthRate: "medium",
    soilMix: "ดินพีทมอสผสมเพอร์ไลท์ 50:50 กักเก็บความชื้นได้พอดีแต่โปร่งสบาย",
    fertilizerNote: "ปุ๋ยละลายช้าสูตรเสมอ ทุก 3 เดือน",
    propagation: "ตัดครึ่งใบปักชำลงดินชื้น เกิดต้นใหม่จากเส้นใบ",
    shopNote: "บ้านไหนเลี้ยงแมว แนะนำต้นนี้เป็นอันดับ 1 ปลอดภัยแน่นอน ใบหนาอุ้มน้ำ อย่ารดน้ำบ่อยจนดินแฉะ",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1612363228108-54b9df919246?auto=format&fit=crop&w=1200&q=80",
        altTh: "เปปเปอร์โรเมียแตงโม ใบกลมน่ารักปลอดภัยกับสัตว์เลี้ยง",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 4,
      waterDaysRainy: 7,
      waterDaysCool: 6,
      fertilizeDays: 60,
      fertilizePauseMonths: [],
      repotMonths: 18,
      pestCheckDays: 20,
      notesTh: "รดน้ำเฉพาะโคนต้น เลี่ยงการรดน้ำโดนใบตรงๆ ในร่ม",
    },
    problems: [
      {
        symptomTh: "ก้านใบเปื่อยและหลุดร่วงง่าย",
        causeTh: "น้ำขังโคนก้าน ดินแน่นเกินไป",
        fixTh: "ลดน้ำ เปลี่ยนกระถางดินเผาขนาดเล็กเพื่อช่วยระบายน้ำ",
        severity: "medium",
      }
    ],
  },
  {
    slug: "calathea-orbifolia",
    nameTh: "คล้าใบตอง คล้าออร์บิโฟเลีย",
    nameEn: "Calathea Orbifolia",
    nameSci: "Goeppertia orbifolia",
    aliases: ["คล้าใบตอง", "ออร์บิโฟเลีย", "Calathea"],
    family: "Marantaceae",
    summary: "ใบกลมใหญ่ลายทางสีเขียวและเงินพาดสลับ ปลอดภัยกับสัตว์เลี้ยง หุบใบยามค่ำคืนเหมือนพนมมือ",
    light: "shade",
    waterNeed: "medium",
    placement: ["indoor", "bathroom"],
    difficulty: 4,
    petSafe: "safe",
    matureSize: "md",
    matureHeightCm: 80,
    growthRate: "medium",
    soilMix: "พีทมอส 40% + ขุยมะพร้าวล้างสารแทนนิน 30% + เพอร์ไลท์ 30%",
    fertilizerNote: "ปุ๋ยอินทรีย์น้ำเจือจาง เดือนละครั้ง ห้ามใช้ปุ๋ยเคมีเข้มข้น",
    propagation: "แยกกอช่วงฤดูฝน",
    shopNote: "คล้าชอบความชื้นสูงและน้ำสะอาด ถ้าน้ำประปามีคลอรีนสูงปลายใบจะไหม้ แนะนำให้ใช้น้ำฝนหรือน้ำกรองในการรด",
    stockStatus: "made_to_order",
    images: [
      {
        url: "https://images.unsplash.com/photo-1598880940371-c756e015fea1?auto=format&fit=crop&w=1200&q=80",
        altTh: "คล้าออร์บิโฟเลีย ใบกลมลายพริ้วสวยงาม",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 2,
      waterDaysRainy: 4,
      waterDaysCool: 4,
      fertilizeDays: 45,
      fertilizePauseMonths: [12, 1],
      repotMonths: 12,
      pestCheckDays: 10,
      notesTh: "คอยรักษาดินให้ชื้นแต่ไม่แฉะ ฉีดละอองน้ำรอบพุ่มใบเพิ่มความชื้น",
    },
    problems: [
      {
        symptomTh: "ขอบใบแห้งม้วนงอเข้าหาตัว",
        causeTh: "อากาศแห้งจัด หรือขาดน้ำ",
        fixTh: "วางบนถาดรองหินกรวดหล่อน้ำ ฉีดฟ็อกกี้ละอองละเอียดรอบพุ่ม",
        severity: "medium",
      }
    ],
  },
  {
    slug: "anthurium-clarinervium",
    nameTh: "หน้าวัวใบ คลาริเนอร์เวียม",
    nameEn: "Velvet Cardboard Anthurium",
    nameSci: "Anthurium clarinervium",
    aliases: ["หน้าวัวหัวใจ", "คลาริเนอร์เวียม", "หน้าวัวใบกำมะหยี่"],
    family: "Araceae",
    summary: "ใบรูปหัวใจหนาเนื้อกำมะหยี่ เส้นใบสีขาวเงินเด่นชัด ประณีตงดงามราวกระดาษการ์ดทำมือ",
    light: "indoor_bright",
    waterNeed: "low",
    placement: ["indoor", "balcony"],
    difficulty: 3,
    petSafe: "toxic",
    matureSize: "sm",
    matureHeightCm: 45,
    growthRate: "slow",
    soilMix: "เปลือกสนนิวซีแลนด์ 50% + กาบมะพร้าวสับ 30% + เพอร์ไลท์ 20% แบบไม้รากอากาศ",
    fertilizerNote: "ปุ๋ยออสโมโค้ทเม็ดช้า ทุก 4 เดือน",
    propagation: "เพาะเมล็ดจากผลสุก หรือตัดยอด",
    shopNote: "เป็นพืชอิงอาศัย รากชอบอากาศถ่ายเทสะดวก อย่าใช้ดินเหนียวแน่นเด็ดขาด ปลูกในกระถางดินเผารูเยอะจะโตดีมาก",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1615211018083-49033324c44f?auto=format&fit=crop&w=1200&q=80",
        altTh: "หน้าวัวใบคลาริเนอร์เวียม ใบหัวใจลึกซึ้ง",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 3,
      waterDaysRainy: 6,
      waterDaysCool: 5,
      fertilizeDays: 60,
      fertilizePauseMonths: [],
      repotMonths: 18,
      pestCheckDays: 14,
      notesTh: "รากชอบโปร่ง พ่นน้ำให้ชุ่มโชกแล้วปล่อยให้แห้งก่อนรดรอบถัดไป",
    },
    problems: [
      {
        symptomTh: "ใบเหลืองใสและนิ่ม มีกลิ่นชื้น",
        causeTh: "วัสดุปลูกแน่น ระบายน้ำช้า รากขาดอากาศ",
        fixTh: "เปลี่ยนมาใช้วัสดุโปร่ง เช่น เปลือกสนและหินภูเขาไฟ",
        severity: "high",
      }
    ],
  },
  {
    slug: "syngonium-albo-variegata",
    nameTh: "ออมเพชร ซิงโกเนียมด่างขาว",
    nameEn: "Syngonium Albo Variegated",
    nameSci: "Syngonium podophyllum 'Albo-Variegatum'",
    aliases: ["ออมเพชร", "ซิงโกเนียมด่าง", "เงินไหลมาด่างขาว"],
    family: "Araceae",
    summary: "ไม้มงคลนามเงินไหลมา ลายด่างขาวกระจายบนใบรูปลูกศร โตไว เลี้ยงง่าย ตัดชำขยายพันธุ์สนุก",
    light: "indoor_bright",
    waterNeed: "medium",
    placement: ["indoor", "balcony"],
    difficulty: 1,
    petSafe: "toxic",
    matureSize: "md",
    matureHeightCm: 60,
    growthRate: "fast",
    soilMix: "ดินใบก้ามปูร่วน ผสมกาบมะพร้าวสับและมูลไส้เดือน",
    fertilizerNote: "ปุ๋ยคอกหมัก หรือปุ๋ยบำรุงใบ เดือนละครั้ง",
    propagation: "ตัดกิ่งชำน้ำ รากออกเร็วมาก",
    shopNote: "ตัดยอดบ่อยๆ จะช่วยกระตุ้นให้แตกพุ่มกลมสวย ถ้าอยากให้ใบใหญ่ขึ้น ให้หาหลักกาบมะพร้าวให้น้องเกาะเลื้อย",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1628744876497-eb30460be9f6?auto=format&fit=crop&w=1200&q=80",
        altTh: "ออมเพชรด่างขาว ลวดลายสวยสะดุดตา",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 3,
      waterDaysRainy: 5,
      waterDaysCool: 4,
      fertilizeDays: 30,
      fertilizePauseMonths: [],
      repotMonths: 12,
      pestCheckDays: 14,
      notesTh: "ชอบความชื้นปานกลาง แดดรำไรสว่าง ดินแห้งนิดหน่อยก็ทนได้",
    },
    problems: [
      {
        symptomTh: "สีด่างขาวเริ่มเลือนหาย กลายเป็นเขียวล้วน",
        causeTh: "แสงสว่างไม่พอ",
        fixTh: "ตัดแต่งยอดเขียวทิ้ง และย้ายไปจุดที่มีแสงรำไรสว่างขึ้น",
        severity: "low",
      }
    ],
  },
  {
    slug: "chamaedorea-seifrizii",
    nameTh: "ปาล์มไผ่ ฟอกอากาศ",
    nameEn: "Bamboo Palm",
    nameSci: "Chamaedorea seifrizii",
    aliases: ["ปาล์มไผ่", "ปาล์มห้องรับแขก", "Bamboo Palm"],
    family: "Arecaceae",
    summary: "ฟอร์มใบโปร่งพริ้วไหวสไตล์ทรอปิคอล ปลอดภัยกับสัตว์เลี้ยง ฟอกสารเบนซินและฟอร์มาลดีไฮด์ในอาคาร",
    light: "partial",
    waterNeed: "medium",
    placement: ["indoor", "balcony", "outdoor"],
    difficulty: 1,
    petSafe: "safe",
    matureSize: "lg",
    matureHeightCm: 180,
    growthRate: "medium",
    soilMix: "ดินร่วนปนทราย ผสมปุ๋ยหมักและกาบมะพร้าวสับ ระบายน้ำดี",
    fertilizerNote: "ปุ๋ยบำรุงปาล์ม ทุก 2 เดือน",
    propagation: "แยกหน่อกอ หรือเพาะเมล็ด",
    shopNote: "เหมาะสำหรับห้องนั่งเล่นที่มีน้องหมาน้องแมววิ่งเล่น ใบไม่เป็นพิษ ทนแสงไฟนีออนในออฟฟิศได้ดี",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1610444583716-1f7c7df9bf04?auto=format&fit=crop&w=1200&q=80",
        altTh: "ปาล์มไผ่ฟอร์มโปร่ง สบายตาปลอดภัยกับสัตว์เลี้ยง",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 3,
      waterDaysRainy: 6,
      waterDaysCool: 5,
      fertilizeDays: 60,
      fertilizePauseMonths: [],
      repotMonths: 24,
      pestCheckDays: 20,
      notesTh: "รดน้ำจนชุ่มเมื่อผิวดินแห้ง หลีกเลี่ยงน้ำขังแฉะในจานรอง",
    },
    problems: [
      {
        symptomTh: "ปลายใบแห้งสีน้ำตาลเป็นฝอย",
        causeTh: "ขาดน้ำ หรือโดนแดดเที่ยงตรงเผาใบ",
        fixTh: "ตัดปลายแห้งทิ้ง ขยับเข้าแดดรำไร และรดน้ำให้สม่ำเสมอ",
        severity: "low",
      }
    ],
  },
  {
    slug: "philodendron-birkin",
    nameTh: "ฟิโลเดนดรอน เบอร์กิ้น",
    nameEn: "Philodendron Birkin",
    nameSci: "Philodendron 'Birkin'",
    aliases: ["เบอร์กิ้น", "ฟิโลเบอร์กิ้น", "Birkin"],
    family: "Araceae",
    summary: "ลายเส้นสีขาวครีมวาดคมกริบบนพื้นใบเขียวเข้ม ทรงพุ่มกลมกะทัดรัด ไม่เลื้อย วางโต๊ะทำงานสวยหรู",
    light: "indoor_bright",
    waterNeed: "low",
    placement: ["indoor", "balcony"],
    difficulty: 1,
    petSafe: "toxic",
    matureSize: "sm",
    matureHeightCm: 45,
    growthRate: "slow",
    soilMix: "กาบมะพร้าวสับ + พีทมอส + เพอร์ไลท์ เน้นโปร่งระบายน้ำ",
    fertilizerNote: "ปุ๋ยละลายช้าเม็ด ทุก 3 เดือน",
    propagation: "แยกหน่อข้าง หรือตัดยอด",
    shopNote: "ยิ่งโต ลายเส้นสีขาวจะยิ่งเด่นชัดขึ้น วางบนโต๊ะทำงานช่วยพักสายตาได้ดีมาก และไม่เกะกะพื้นที่",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1620127814146-d1a5be298980?auto=format&fit=crop&w=1200&q=80",
        altTh: "ฟิโลเดนดรอน เบอร์กิ้น ลายเส้นขาวคมชัด",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 4,
      waterDaysRainy: 7,
      waterDaysCool: 5,
      fertilizeDays: 45,
      fertilizePauseMonths: [],
      repotMonths: 18,
      pestCheckDays: 14,
      notesTh: "ดินแห้ง 50% ของกระถางแล้วค่อยรดน้ำ",
    },
    problems: [
      {
        symptomTh: "ใบใหม่กลายเป็นสีเขียวไม่มีลายเส้น",
        causeTh: "การกลายพันธุ์ย้อนกลับ (Reversion) หรือแสงสว่างไม่พอ",
        fixTh: "เพิ่มแสงแดดรำไรสว่าง ถ้าใบยังเขียวล้วน ให้ตัดยอดเพื่อให้แตกตาล่างที่มีลาย",
        severity: "low",
      }
    ],
  },
  {
    slug: "tradescantia-zebrina",
    nameTh: "ก้ามปูหลุดด่างชมพู นานุค",
    nameEn: "Tradescantia Nanouk",
    nameSci: "Tradescantia fluminensis 'Nanouk'",
    aliases: ["ก้ามปูหลุด", "นานุค", "Nanouk"],
    family: "Commelinaceae",
    summary: "สีชมพูมาเจนต้าตัดกับเขียวสดใส เลี้ยงง่าย ทนทาน แดดยิ่งดีสียิ่งหวานสว่าง",
    light: "partial",
    waterNeed: "medium",
    placement: ["indoor", "balcony", "outdoor"],
    difficulty: 1,
    petSafe: "toxic",
    matureSize: "xs",
    matureHeightCm: 30,
    growthRate: "fast",
    soilMix: "ดินปลูกทั่วไปผสมขุยมะพร้าวและทรายหยาบ",
    fertilizerNote: "ปุ๋ยบำรุงใบ เดือนละครั้ง",
    propagation: "หักกิ่งปักชำลงดิน รดน้ำ ติดรากภายใน 5 วัน",
    shopNote: "วางตรงหน้าต่างที่รับแดดเช้า สีชมพูจะสดใสเงางามเป็นพิเศษ หมั่นเด็ดยอดเพื่อกระตุ้นให้แตกพุ่มแน่น",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?auto=format&fit=crop&w=1200&q=80",
        altTh: "ก้ามปูหลุดนานุค สีชมพูหวานสดชื่น",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 3,
      waterDaysRainy: 5,
      waterDaysCool: 4,
      fertilizeDays: 30,
      fertilizePauseMonths: [],
      repotMonths: 12,
      pestCheckDays: 14,
      notesTh: "ชอบดินชื้นปานกลาง รดน้ำให้โดนดิน อย่าเทขังบนใบแน่น",
    },
    problems: [
      {
        symptomTh: "กิ่งยืดยาว ใบสีเขียวซีด สีชมพูจางหาย",
        causeTh: "ขาดแสงแดด",
        fixTh: "ย้ายไปรับแดดเช้า 3-4 ชั่วโมง สีชมพูจะกลับมาเข้ม",
        severity: "low",
      }
    ],
  },
  {
    slug: "acanthocereus-tetragonus",
    nameTh: "แคคตัส ปราสาทนางฟ้า",
    nameEn: "Fairy Castle Cactus",
    nameSci: "Acanthocereus tetragonus",
    aliases: ["คอนโดนางฟ้า", "ปราสาทนางฟ้า", "แคคตัส"],
    family: "Cactaceae",
    summary: "รูปทรงคล้ายปราสาทในเทพนิยาย มีเสาสูงต่ำลดหลั่นกัน เลี้ยงง่ายสุดๆ แทบไม่ต้องดูแล",
    light: "full_sun",
    waterNeed: "low",
    placement: ["balcony", "outdoor", "indoor"],
    difficulty: 1,
    petSafe: "safe",
    matureSize: "sm",
    matureHeightCm: 40,
    growthRate: "slow",
    soilMix: "ดินแคคตัสระบายน้ำเร็วพิเศษ หินภูเขาไฟ เพอร์ไลท์ ทรายหยาบ",
    fertilizerNote: "ปุ๋ยแคคตัส ทุก 3-4 เดือน",
    propagation: "เด็ดกิ่งยอดเล็กๆ ผึ่งแผลแห้ง 3 วันแล้วปักชำ",
    shopNote: "ถ้าเลี้ยงในห้อง ต้องวางริมหน้าต่างแดดส่องถึง รดน้ำเดือนละ 2 ครั้งพอ ดินแห้งคือรอด ดินแฉะคือเน่า",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?auto=format&fit=crop&w=1200&q=80",
        altTh: "แคคตัสปราสาทนางฟ้า ทรงเสาสูงต่ำสวยงาม",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 10,
      waterDaysRainy: 18,
      waterDaysCool: 14,
      fertilizeDays: 90,
      fertilizePauseMonths: [11, 12, 1],
      repotMonths: 24,
      pestCheckDays: 30,
      notesTh: "รดน้ำจนไหลออกก้นกระถาง แล้วรอจนดินแห้งสนิททั้งกระถาง",
    },
    problems: [
      {
        symptomTh: "เสาลำต้นเริ่มนิ่ม เปลี่ยนเป็นสีน้ำตาลจากโคน",
        causeTh: "รดน้ำบ่อยเกินไป รากเน่าโคนเน่า",
        fixTh: "ตัดยอดส่วนที่ยังเขียวแข็งทิ้งไว้ให้แห้งแล้วปักชำใหม่ ส่วนที่เน่าทิ้ง",
        severity: "high",
      }
    ],
  },
  {
    slug: "monstera-deliciosa",
    nameTh: "มอนสเตอร่า ไจแอนท์",
    nameEn: "Swiss Cheese Plant / Giant Monstera",
    nameSci: "Monstera deliciosa",
    aliases: ["มอนสเตอร่า", "มอนเขียว", "ไจแอนท์", "Monstera"],
    family: "Araceae",
    summary: "ราชาแห่งไม้ใบ ใบฉลุลายธรรมชาติทรงพลัง ทนทาน โตไว เสริมบรรยากาศทรอปิคอลให้บ้าน",
    light: "indoor_bright",
    waterNeed: "medium",
    placement: ["indoor", "balcony", "outdoor"],
    difficulty: 1,
    petSafe: "toxic",
    matureSize: "xl",
    matureHeightCm: 220,
    growthRate: "fast",
    soilMix: "กาบมะพร้าวสับ 50% + ใบก้ามปูหมัก 30% + เพอร์ไลท์ 20%",
    fertilizerNote: "ปุ๋ยเม็ดละลายช้าทุก 3 เดือน",
    propagation: "ตัดชำกิ่งข้อรากอากาศ",
    shopNote: "มอนสเตอร่าเขียวเลี้ยงง่ายกว่ามอนด่างเยอะมาก ทนทาน โตเร็ว เหมาะกับผู้เริ่มต้นที่อยากได้ต้นไม้ไซส์ใหญ่ประดับห้อง",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=1200&q=80",
        altTh: "มอนสเตอร่าไจแอนท์ใบฉลุใหญ่สมบูรณ์",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 3,
      waterDaysRainy: 6,
      waterDaysCool: 5,
      fertilizeDays: 45,
      fertilizePauseMonths: [],
      repotMonths: 12,
      pestCheckDays: 14,
      notesTh: "ใช้นิ้วจิ้มดินลึก 2 นิ้ว แห้งแล้วค่อยรด",
    },
    problems: [
      {
        symptomTh: "ใบใหม่ออกมาเป็นใบเรียบ ไม่ฉลุรู",
        causeTh: "ต้นยังเด็ก หรือแสงแดดไม่เพียงพอ",
        fixTh: "เพิ่มแสงสว่างรำไร และปักเสาหลักให้เกาะขึ้นที่สูง",
        severity: "low",
      }
    ],
  },
  {
    slug: "ficus-elastica-variegata",
    nameTh: "ยางอินเดียด่าง ทริคัลเลอร์",
    nameEn: "Variegated Rubber Tree",
    nameSci: "Ficus elastica 'Tineke'",
    aliases: ["ยางด่าง", "ยางอินเดียด่าง", "ทิเนเก้"],
    family: "Moraceae",
    summary: "ใบหนาด่างลายหินอ่อนสีครีม เขียว และชมพูพาสเทล สวยหรูสไตล์โมเดิร์น",
    light: "indoor_bright",
    waterNeed: "low",
    placement: ["indoor", "balcony"],
    difficulty: 2,
    petSafe: "toxic",
    matureSize: "lg",
    matureHeightCm: 180,
    growthRate: "medium",
    soilMix: "ดินใบก้ามปู 40% + กาบมะพร้าวสับ 30% + เพอร์ไลท์ 30%",
    fertilizerNote: "ปุ๋ยละลายช้าสูตรเสมอ ทุก 2-3 เดือน",
    propagation: "ตอนกิ่ง หรือปักชำยอด",
    shopNote: "ยางด่างต้องการแสงมากกว่ายางดำ เพื่อรักษาขอบสีครีมชมพูไว้ ควรวางริมหน้าต่างที่มีแดดส่องรำไร",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1596724803362-e6113b2e75dc?auto=format&fit=crop&w=1200&q=80",
        altTh: "ยางอินเดียด่างสีพาสเทลละมุน",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 4,
      waterDaysRainy: 7,
      waterDaysCool: 6,
      fertilizeDays: 60,
      fertilizePauseMonths: [],
      repotMonths: 18,
      pestCheckDays: 14,
      notesTh: "ดินแห้งค่อยรด ระวังน้ำขังจานรอง",
    },
    problems: [
      {
        symptomTh: "ขอบใบสีครีมเปลี่ยนเป็นสีน้ำตาลไหม้",
        causeTh: "โดนแดดแรงตรงๆ ช่วงบ่ายเผาใบ",
        fixTh: "ติดม่านกรองแสง หรือขยับเข้าด้านในห้อง 1 เมตร",
        severity: "medium",
      }
    ],
  },
  {
    slug: "asplenium-nidus",
    nameTh: "เฟิร์นข้าหลวง หลังลาย",
    nameEn: "Bird's Nest Fern",
    nameSci: "Asplenium nidus",
    aliases: ["เฟิร์นข้าหลวง", "ข้าหลวงหลังลาย", "Bird Nest Fern"],
    family: "Aspleniaceae",
    summary: "ใบเรียวยาวสีเขียวตองอ่อนเรียงตัวเป็นรูปถ้วยคล้ายรังนก ปลอดภัยกับสัตว์เลี้ยง ชอบความชื้น",
    light: "shade",
    waterNeed: "high",
    placement: ["indoor", "bathroom", "balcony"],
    difficulty: 2,
    petSafe: "safe",
    matureSize: "md",
    matureHeightCm: 80,
    growthRate: "medium",
    soilMix: "กาบมะพร้าวสับ 70% + รากเฟิร์นหรือสแฟกนัมมอส 30% ระบายน้ำและโปร่งลม",
    fertilizerNote: "ปุ๋ยน้ำอินทรีย์เจือจางมาก รดเดือนละครั้ง",
    propagation: "เพาะสปอร์ใต้ใบ หรือแยกกอ",
    shopNote: "เวลารดน้ำ อย่าเทน้ำลงไปขังตรงใจกลางรังนกตรงๆ เพราะยอดอ่อนอาจเน่าได้ ให้รดรอบๆ โคนต้น",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1599685315640-9ceab2f58944?auto=format&fit=crop&w=1200&q=80",
        altTh: "เฟิร์นข้าหลวง กางใบสวยสมบูรณ์",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 2,
      waterDaysRainy: 4,
      waterDaysCool: 3,
      fertilizeDays: 45,
      fertilizePauseMonths: [],
      repotMonths: 18,
      pestCheckDays: 14,
      notesTh: "ชอบอากาศชื้น รดรอบกระถาง เลี่ยงกลางยอด",
    },
    problems: [
      {
        symptomTh: "ใจกลางยอดเน่าเป็นสีดำ ยอดอ่อนไม่ยอมกาง",
        causeTh: "น้ำขังตรงกลางถ้วยรังนก",
        fixTh: "ซับน้ำออกให้แห้ง วางในที่ลมโกรก",
        severity: "high",
      }
    ],
  },
  {
    slug: "aglaonema-ruby",
    nameTh: "อโกลนีมา บัลลังก์ทับทิม",
    nameEn: "Aglaonema Super Red",
    nameSci: "Aglaonema 'Ruby Super Red'",
    aliases: ["อโกลนีมา", "บัลลังก์ทับทิม", "แก้วกาญจนาสีแดง"],
    family: "Araceae",
    summary: "ไม้มงคลสีแดงทับทิมสดใส เสริมบารมีและโชคลาภ ทนทานในที่แสงน้อย เลี้ยงง่ายทนแล้ง",
    light: "low_light",
    waterNeed: "low",
    placement: ["indoor", "balcony"],
    difficulty: 1,
    petSafe: "toxic",
    matureSize: "sm",
    matureHeightCm: 45,
    growthRate: "slow",
    soilMix: "ดินร่วนผสมกาบมะพร้าวสับและเพอร์ไลท์",
    fertilizerNote: "ปุ๋ยละลายช้าสูตรเสมอ ทุก 3 เดือน",
    propagation: "ตัดยอดปักชำ หรือแยกหน่อ",
    shopNote: "ต้นไม้มงคลที่คนนิยมให้เป็นของขวัญขึ้นบ้านใหม่ สีแดงสดคงทนแม้เลี้ยงในที่ร่ม",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1200&q=80",
        altTh: "อโกลนีมาสีแดงทับทิมสดใส",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 4,
      waterDaysRainy: 7,
      waterDaysCool: 6,
      fertilizeDays: 60,
      fertilizePauseMonths: [],
      repotMonths: 18,
      pestCheckDays: 20,
      notesTh: "รดน้ำสัปดาห์ละ 1-2 ครั้งเมื่อดินแห้ง",
    },
    problems: [
      {
        symptomTh: "ปลายใบแห้งเป็นสีน้ำตาล",
        causeTh: "อากาศแห้งจัด หรือรดน้ำไม่ทั่วถึง",
        fixTh: "ตัดแต่งส่วนแห้งออก รดน้ำจนน้ำซึมออกก้นกระถาง",
        severity: "low",
      }
    ],
  },
  {
    slug: "sansevieria-hahnii",
    nameTh: "ลิ้นมังกร ฮานิอาย แคะ",
    nameEn: "Bird's Nest Snake Plant",
    nameSci: "Sansevieria trifasciata 'Hahnii'",
    aliases: ["ฮานิอาย", "ลิ้นมังกรแคระ", "Hahnii"],
    family: "Asparagaceae",
    summary: "ต้นเล็กน่ารัก ทรงกุหลาบหิน วางบนโต๊ะทำงานได้พอดี ปล่อยออกซิเจนตอนกลางคืน ดูดสารพิษ",
    light: "low_light",
    waterNeed: "low",
    placement: ["indoor", "bathroom", "balcony"],
    difficulty: 1,
    petSafe: "toxic",
    matureSize: "xs",
    matureHeightCm: 20,
    growthRate: "slow",
    soilMix: "ดินแคคตัส หรือดินร่วนผสมทรายหยาบและเพอร์ไลท์",
    fertilizerNote: "ปุ๋ยละลายช้าปีละ 2 ครั้ง",
    propagation: "แยกหน่อข้าง หรือตัดใบปักชำ",
    shopNote: "เหมาะมากสำหรับคนที่ไม่ค่อยมีเวลารดน้ำ หรือเดินทางบ่อย อยู่รอดได้สบายแม้ไม่มีใครสนใจ",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1593482892290-f54927ae1bf6?auto=format&fit=crop&w=1200&q=80",
        altTh: "ลิ้นมังกรแคระฮานิอาย วางโต๊ะทำงาน",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 7,
      waterDaysRainy: 12,
      waterDaysCool: 10,
      fertilizeDays: 90,
      fertilizePauseMonths: [],
      repotMonths: 24,
      pestCheckDays: 30,
      notesTh: "รดน้ำรอบกระถาง เลี่ยงน้ำขังกลางกอ",
    },
    problems: [
      {
        symptomTh: "ใบชั้นนอกนิ่มและเหี่ยวย่น",
        causeTh: "ดินแห้งเกินไปนานมาก หรือรากเน่า",
        fixTh: "ตรวจดิน ถ้าแห้งผากให้รดน้ำ ถ้านิ่มเละให้เปลี่ยนดิน",
        severity: "medium",
      }
    ],
  },
  {
    slug: "alocasia-macrorrhizos-variegata",
    nameTh: "บอนกระดาดด่างขาว",
    nameEn: "Variegated Giant Taro",
    nameSci: "Alocasia macrorrhizos 'Variegata'",
    aliases: ["บอนกระดาดด่าง", "บอนด่าง", "กระดาดด่าง"],
    family: "Araceae",
    summary: "ใบใหญ่โตอลังการ ลายด่างขาวกระจายเหมือนผลงานศิลปะชิ้นเอก ฟอร์มโดดเด่นสะดุดตา",
    light: "partial",
    waterNeed: "high",
    placement: ["balcony", "outdoor", "indoor"],
    difficulty: 3,
    petSafe: "toxic",
    matureSize: "xl",
    matureHeightCm: 200,
    growthRate: "fast",
    soilMix: "ดินใบก้ามปู 50% + กาบมะพร้าวสับ 30% + มูลวัวเก่า 20%",
    fertilizerNote: "ปุ๋ยคอกหมักทุกเดือน และปุ๋ยละลายช้า",
    propagation: "แยกหน่อ หรือเพาะชำไข่ใต้ดิน",
    shopNote: "บอนกระดาดกินปุ๋ยและน้ำเก่งมาก หากปลูกลงกระถางใหญ่กลางแจ้งแดดรำไรจะโตไวมาก รดน้ำทุกวันได้เลยในหน้าร้อน",
    stockStatus: "made_to_order",
    images: [
      {
        url: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=1200&q=80",
        altTh: "บอนกระดาดด่างขาว ใบอลังการ",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 1,
      waterDaysRainy: 3,
      waterDaysCool: 2,
      fertilizeDays: 20,
      fertilizePauseMonths: [],
      repotMonths: 12,
      pestCheckDays: 10,
      notesTh: "ชอบน้ำและความชื้นสูง ดินต้องชุ่มชื้นเสมอ",
    },
    problems: [
      {
        symptomTh: "ไรแดงขึ้นใต้ใบ มีใยแมงมุมละเอียด",
        causeTh: "อากาศร้อนแห้ง ลมพัดแรง",
        fixTh: "ฉีดน้ำล้างใต้ใบแรงๆ หรือพ่นน้ำมันสะเดาอินทรีย์",
        severity: "medium",
      }
    ],
  },
  {
    slug: "philodendron-white-wizard",
    nameTh: "ฟิโลเดนดรอน ไวท์วิซาร์ด",
    nameEn: "Philodendron White Wizard",
    nameSci: "Philodendron 'White Wizard'",
    aliases: ["ไวท์วิซาร์ด", "พ่อมดขาว", "White Wizard"],
    family: "Araceae",
    summary: "ด่างขาวหิมะตัดกับก้านใบสีเขียวล้วน เลี้ยงง่ายกว่าอัลโบ แข็งแรงและด่างเสถียร",
    light: "indoor_bright",
    waterNeed: "medium",
    placement: ["indoor", "balcony"],
    difficulty: 2,
    petSafe: "toxic",
    matureSize: "md",
    matureHeightCm: 90,
    growthRate: "medium",
    soilMix: "กาบมะพร้าวสับ 40% + เปลือกสน 30% + เพอร์ไลท์ 20% + มูลไส้เดือน 10%",
    fertilizerNote: "ปุ๋ยบำรุงใบทางรากเดือนละครั้ง",
    propagation: "ตัดยอดปักชำข้อ",
    shopNote: "ไวท์วิซาร์ดก้านใบจะเป็นสีเขียวล้วน (ต่างจาก White Princess ที่ก้านมีแถบชมพู) ดูแลแลง่ายและด่างขาวไม่ค่อยไหม้",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1620127814146-d1a5be298980?auto=format&fit=crop&w=1200&q=80",
        altTh: "ไวท์วิซาร์ด ด่างขาวสะอาดตา",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 3,
      waterDaysRainy: 6,
      waterDaysCool: 5,
      fertilizeDays: 30,
      fertilizePauseMonths: [],
      repotMonths: 12,
      pestCheckDays: 14,
      notesTh: "ดินแห้ง 2 นิ้วค่อยรดน้ำ",
    },
    problems: [
      {
        symptomTh: "ปลายใบใหม่ไหม้ก่อนคลี่",
        causeTh: "ความชื้นในอากาศไม่พอ ใบติดขัดตอนคลี่",
        fixTh: "ฉีดละอองน้ำช่วยพยุงตอนใบใหม่กำลังแทงยอด",
        severity: "low",
      }
    ],
  },
  {
    slug: "scindapsus-pictus",
    nameTh: "พลูหัวใจแนบ ซิลเวอร์ซาติน",
    nameEn: "Satin Pothos",
    nameSci: "Scindapsus pictus 'Argyraeus'",
    aliases: ["พลูหัวใจแนบ", "ซาติน", "Satin Pothos"],
    family: "Araceae",
    summary: "ใบรูปหัวใจเคลือบประกายเงินระยิบระยับเมื่อสะท้อนแสง ไม้เลื้อยเสน่ห์แรง ดูแลง่าย",
    light: "indoor_bright",
    waterNeed: "low",
    placement: ["indoor", "balcony", "bathroom"],
    difficulty: 1,
    petSafe: "toxic",
    matureSize: "sm",
    matureHeightCm: 40,
    growthRate: "medium",
    soilMix: "ดินพีทมอสผสมเพอร์ไลท์และกาบมะพร้าวสับ",
    fertilizerNote: "ปุ๋ยน้ำบำรุงใบ เดือนละครั้ง",
    propagation: "ตัดข้อปักชำน้ำ",
    shopNote: "เมื่อมันหิวน้ำ ใบจะม้วนงอเล็กน้อย เป็นสัญญาณธรรมชาติเตือนให้รดน้ำได้อย่างแม่นยำ",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1597055181300-e3633a917c9c?auto=format&fit=crop&w=1200&q=80",
        altTh: "พลูหัวใจแนบ ใบเงินวิบวับสวยงาม",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 4,
      waterDaysRainy: 7,
      waterDaysCool: 5,
      fertilizeDays: 45,
      fertilizePauseMonths: [],
      repotMonths: 18,
      pestCheckDays: 20,
      notesTh: "รดเมื่อใบเริ่มห่อนิดๆ หรือดินแห้ง",
    },
    problems: [
      {
        symptomTh: "ใบเหลืองร่วงเป็นข้อๆ",
        causeTh: "ดินชื้นแฉะเกินไป รากขาดอากาศ",
        fixTh: "ทิ้งระยะการรดน้ำให้นานขึ้น",
        severity: "medium",
      }
    ],
  },
  {
    slug: "alocasia-baginda-dragon-scale",
    nameTh: "อโลคาเซีย เกล็ดมังกร",
    nameEn: "Dragon Scale Alocasia",
    nameSci: "Alocasia baginda 'Dragon Scale'",
    aliases: ["ดราก้อนสเกล", "เกล็ดมังกร", "Dragon Scale"],
    family: "Araceae",
    summary: "ใบหนานูนเป็นลอนคล้ายเกล็ดมังกร สีเขียวมรกตเหลือบเงินตัดกับเส้นใบสีเขียวเข้ม ทรงพลัง",
    light: "indoor_bright",
    waterNeed: "low",
    placement: ["indoor", "balcony"],
    difficulty: 3,
    petSafe: "toxic",
    matureSize: "sm",
    matureHeightCm: 40,
    growthRate: "slow",
    soilMix: "เปลือกสน 40% + เพอร์ไลท์ 30% + พีทมอส 20% + ถ่านชาร์โคล 10%",
    fertilizerNote: "ปุ๋ยเกล็ดเจือจางมาก เดือนละครั้ง",
    propagation: "แยกไข่ใต้ดิน",
    shopNote: "เกล็ดมังกรชอบความชื้นในบรรยากาศสูง แต่อย่าให้ดินแฉะ วางบนถาดหินหล่อน้ำจะโตสวยงามมาก",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1600411833196-7c1f6b1a8b90?auto=format&fit=crop&w=1200&q=80",
        altTh: "อโลคาเซียเกล็ดมังกร พื้นผิวใบสวยงาม",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 4,
      waterDaysRainy: 7,
      waterDaysCool: 6,
      fertilizeDays: 45,
      fertilizePauseMonths: [12],
      repotMonths: 12,
      pestCheckDays: 14,
      notesTh: "ดินแห้งเกือบหมดค่อยรดน้ำ",
    },
    problems: [
      {
        symptomTh: "ใบเหลืองเป็นจุดๆ มีคราบขาวใต้ใบ",
        causeTh: "ไรแดงรบกวน",
        fixTh: "ใช้ฟองน้ำชุบน้ำสบู่อ่อนเช็ดล้างใต้ใบ",
        severity: "medium",
      }
    ],
  },
  {
    slug: "nephrolepis-exaltata",
    nameTh: "เฟิร์นบอสตัน พุ่มฟู",
    nameEn: "Boston Fern",
    nameSci: "Nephrolepis exaltata",
    aliases: ["เฟิร์นบอสตัน", "Boston Fern"],
    family: "Lomariopsidaceae",
    summary: "พุ่มใบแน่นพลิ้วไหวสีเขียวสดใส ดักจับฝุ่นละอองและเพิ่มความชื้นในอากาศ ปลอดภัยกับสัตว์เลี้ยง",
    light: "partial",
    waterNeed: "high",
    placement: ["indoor", "bathroom", "balcony"],
    difficulty: 2,
    petSafe: "safe",
    matureSize: "md",
    matureHeightCm: 70,
    growthRate: "fast",
    soilMix: "กาบมะพร้าวสับละเอียด + พีทมอส + เพอร์ไลท์ อุ้มน้ำดี",
    fertilizerNote: "ปุ๋ยน้ำบำรุงใบ เดือนละครั้ง",
    propagation: "แยกไหลกอต้นลูก",
    shopNote: "เหมาะแขวนในห้องน้ำที่มีหน้าต่างระบายอากาศ หรือระเบียงร่มรำไรที่ลมพัดผ่านเบาๆ",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1599685315640-9ceab2f58944?auto=format&fit=crop&w=1200&q=80",
        altTh: "เฟิร์นบอสตัน พุ่มเขียวชอุ่มสดชื่น",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 2,
      waterDaysRainy: 4,
      waterDaysCool: 3,
      fertilizeDays: 30,
      fertilizePauseMonths: [],
      repotMonths: 12,
      pestCheckDays: 14,
      notesTh: "รักษาความชื้นสม่ำเสมอ พ่นละอองน้ำเป็นประจำ",
    },
    problems: [
      {
        symptomTh: "ใบแห้งกรอบร่วงเป็นฝอยเกลื่อนพื้น",
        causeTh: "อากาศแห้งเกินไป หรือขาดน้ำ",
        fixTh: "แช่กระถางในกะละมังน้ำ 15 นาที แล้วยกสะเด็ดน้ำ",
        severity: "medium",
      }
    ],
  },
  {
    slug: "calathea-makoyana",
    nameTh: "คล้าแววมยุรา นกยูงรำแพน",
    nameEn: "Peacock Plant",
    nameSci: "Goeppertia makoyana",
    aliases: ["คล้าแววมยุรา", "นกยูงรำแพน", "Peacock Plant"],
    family: "Marantaceae",
    summary: "ลวดลายบนใบพลิ้วไหวประณีตราวดั่งหางนกยูง หลังใบสีม่วงแดงกำมะหยี่ ปลอดภัยกับสัตว์เลี้ยง 100%",
    light: "shade",
    waterNeed: "medium",
    placement: ["indoor", "bathroom"],
    difficulty: 3,
    petSafe: "safe",
    matureSize: "sm",
    matureHeightCm: 45,
    growthRate: "medium",
    soilMix: "พีทมอส 50% + เพอร์ไลท์ 30% + ขุยมะพร้าว 20%",
    fertilizerNote: "ปุ๋ยอินทรีย์น้ำเจือจาง รดเดือนละครั้ง",
    propagation: "แยกกอตอนเปลี่ยนกระถาง",
    shopNote: "อย่าวางโดนแดดตรงเด็ดขาด ลายใบจะไหม้และสีม่วงหลังใบจะซีด ให้แสงร่มรำไรจะสวยที่สุด",
    stockStatus: "seasonal",
    images: [
      {
        url: "https://images.unsplash.com/photo-1598880940371-c756e015fea1?auto=format&fit=crop&w=1200&q=80",
        altTh: "คล้าแววมยุรา ลายนกยูงประณีต",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 2,
      waterDaysRainy: 4,
      waterDaysCool: 4,
      fertilizeDays: 45,
      fertilizePauseMonths: [12],
      repotMonths: 12,
      pestCheckDays: 14,
      notesTh: "ดินชื้นปานกลาง รดด้วยน้ำกรองหรือน้ำพัก",
    },
    problems: [
      {
        symptomTh: "ใบไม่ยอมพนมขึ้นตอนกลางคืน",
        causeTh: "ความชื้นต่ำ หรือมีแสงไฟส่องสว่างตลอดคืน",
        fixTh: "เพิ่มความชื้น และวางในจุดที่มืดสนิทในเวลากลางคืน",
        severity: "low",
      }
    ],
  },
  {
    slug: "zamioculcas-zamiifolia-green",
    nameTh: "กวักมรกตเขียว ดั้งเดิม",
    nameEn: "Classic Green ZZ Plant",
    nameSci: "Zamioculcas zamiifolia",
    aliases: ["กวักเขียว", "กวักมรกต", "ZZ Plant"],
    family: "Araceae",
    summary: "ไม้มงคลยอดนิยม ใบเขียวเข้มมันวาวสะท้อนแสง ทนทานต่อการลืมรดน้ำ อึดถึกทนที่สุด",
    light: "low_light",
    waterNeed: "low",
    placement: ["indoor", "balcony", "bathroom"],
    difficulty: 1,
    petSafe: "toxic",
    matureSize: "md",
    matureHeightCm: 80,
    growthRate: "medium",
    soilMix: "ดินปลูกทั่วไปผสมหินภูเขาไฟและกาบมะพร้าวสับ ระบายน้ำดี",
    fertilizerNote: "ปุ๋ยเม็ดละลายช้า ทุก 3 เดือน",
    propagation: "ปักชำใบ หรือแยกกอ",
    shopNote: "ต้นไม้ยอดฮิตสำหรับเปิดร้านใหม่หรือขึ้นบ้านใหม่ เพราะความหมายดี รักษาง่าย รดน้ำ 10 วันครั้งก็ยังเขียวสด",
    stockStatus: "in_stock",
    images: [
      {
        url: "https://images.unsplash.com/photo-1632207691143-643e2a9a9361?auto=format&fit=crop&w=1200&q=80",
        altTh: "กวักมรกตเขียวใบมันวาว",
        isPrimary: true,
      }
    ],
    careTemplate: {
      waterDaysHot: 6,
      waterDaysRainy: 10,
      waterDaysCool: 8,
      fertilizeDays: 60,
      fertilizePauseMonths: [],
      repotMonths: 24,
      pestCheckDays: 30,
      notesTh: "ดินแห้งสนิทค่อยรดน้ำ ทนแล้งดีเยี่ยม",
    },
    problems: [
      {
        symptomTh: "ใบเหลืองทั้งกิ่ง",
        causeTh: "รดน้ำบ่อยเกินไป หัวใต้ดินเน่า",
        fixTh: "หยุดน้ำ ถอดดูหัวและตัดส่วนเน่าออก",
        severity: "high",
      }
    ],
  }
];
